<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Pengujian extends Model
{
    use HasFactory;

    protected $table = 'pengujians';

    // protected $fillable = [
    //     'id',
    //     'pendaftaran_id',
    //     'kualitasminyakrem',
    //     'kondisibadankacaengseldantempatduduk',
    //     'sistemlampudanapc',
    //     'ukurankendaraan',
    //     'rancanganteknis',
    //     'pemuatan',
    //     'perlengkapan',
    //     'komponenpendukung',
    //     'penempelan',
    //     'kondisiban',
    //     'rangkalandasan',
    //     'motorpenggerak',
    //     'sistempenerusdaya',
    //     'sistempembuangan',
    //     'sistemkemudi',
    //     'sistemsuspensi',
    //     'sistemrem',
    //     'sistembakar',
    //     'sistemrodaroda',
    //     'alatuji_emisiasapbahanbakarsolar',
    //     'alatuji_emisicobahanbakarbensin',
    //     'alatuji_emisihcbahanbakarbensin',
    //     'temp_olimesin',
    //     'putaran_mesin',
    //     'cocor',
    //     'co2',
    //     'o2',
    //     'lamda',
    //     'alatuji_remutamatotalgayapengereman',
    //     'effsumbu1',
    //     'effsumbu2',
    //     'effsumbu3',
    //     'effsumbu4',
    //     'alatuji_remutamaselisihgayapengeremanrodakirikanan1',
    //     'alatuji_remutamaselisihgayapengeremanrodakirikanan2',
    //     'alatuji_remutamaselisihgayapengeremanrodakirikanan3',
    //     'alatuji_remutamaselisihgayapengeremanrodakirikanan4',
    //     'alatuji_remparkirtangan',
    //     'alatuji_kincuprodadepan',
    //     'alatuji_tingkatkebisingan',
    //     'alatuji_lampuutamakekuatanpancarlampukanan',
    //     'alatuji_lampuutamakekuatanpancarlampukiri',
    //     'alatuji_lampuutamapenyimpanganlampukanan',
    //     'alatuji_lampuutamapenyimpanganlampukiri',
    //     'alatuji_penunjukkecepatan',
    //     'alatuji_kedalamanalurban',
    //     'tgluji',
    //     'tglujiulang',
    //     'masaberlakuuji',
    //     'statuslulusuji',
    //     'idpenguji',
    //     'gayaremkiris1',
    //     'gayaremkiris2',
    //     'gayaremkiris3',
    //     'gayaremkiris4',
    //     'gayaremkanans1',
    //     'gayaremkanans2',
    //     'gayaremkanans3',
    //     'gayaremkanans4',
    //     'pos1',
    //     'catatanpos1',
    //     'user_pos1',
    //     'pos2',
    //     'catatanpos2',
    //     'user_pos2',
    //     'pos3',
    //     'catatanpos3',
    //     'user_pos3',
    //     'pos4',
    //     'catatanpos4',
    //     'user_pos4',
    //     'verif',
    //     'catatanverif',
    //     'user_verif',
    // ];
}
